TaskManagement/Models/DailyTask.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TaskManagement.Models
{
    public class DailyTask
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        public string Name { get; set; } = "";
        [Required]
        public string Date { get; set; } = "";
        public string? Description { get; set; }
        [Required]
        [DisplayName("Duration (1 ~ 4)")]
        public int Duration { get; set; }
        [Required]
        public float Effort { get; set; }
        [Required]
        public bool IsCompleted { get; set; }

        public Guid UserId { get; set; }
        public User User { get; set; }
        [DisplayName("Category")]
        public Guid CategoryId { get; set; }
        public TaskCategory Category { get; set; } 
    }
}

TaskManagement/ViewModels/DailyTasks/Report.cs
namespace TaskManagement.ViewModels.DailyTasks
{
    public class Report
    {
        public Dictionary<string, decimal> Categories { get; set; } = new Dictionary<string, decimal>();
        public decimal PercentageCompletion { get; set; } = 0;
        public float TotalEffort { get; set; } = 0;
    }
}

TaskManagement/Controllers/DailyTasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaskManagement.IServices;
using TaskManagement.Models;
using TaskManagement.ViewModels.DailyTasks;

namespace TaskManagement.Controllers
{
    [Authorize(Policy = "BasicUserAccount")]
    public class DailyTasksController : Controller
    {

        private IDailyTasksService DailyTasksService { get; set; }
        private ITaskCategoriesService TaskCategoriesService { get; set; }

        public DailyTasksController(IDailyTasksService dailyTasksService, ITaskCategoriesService taskCategoriesService)
        {
            DailyTasksService = dailyTasksService;
            TaskCategoriesService = taskCategoriesService;
        }

        public async Task<IActionResult> Index(string date)
        {
            var dailyTasks = await DailyTasksService.GetTasksByUserAndDate(User.Identity.Name, date);
            // manage the case in which there are no daily tasks!
            Report? report = null;
            if(dailyTasks != null && dailyTasks.Count() > 0)
                report = DailyTasksService.GenerateReport(dailyTasks);
            ViewData["date"] = date;
            ViewData["report"] = report;
            if (report != null && report.TotalEffort > 18)
            {
                ModelState.AddModelError("", "Too much effort, please remove one or more tasks!");
            }
                
            return View(dailyTasks);
        }

        public async Task<IActionResult> Create(string date)
        {
            ViewData["date"] = date;
            ViewData["categories"] = await TaskCategoriesService.GetCategories();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DailyTask dailyTask)
        {
            var dailyTasks = await DailyTasksService.GetTasksByUserAndDate(User.Identity.Name, dailyTask.Date);
            if (DailyTasksService.CheckTotalEffortOverflow(dailyTasks))
            {
                ModelState.AddModelError("", "The effort is already beyond the limit! Please " +
                    "try to edit, delete or mark as completed other tasks");
                ViewData["date"] = dailyTask.Date;
                ViewData["categories"] = await TaskCategoriesService.GetCategories();
                return View(dailyTask);
            }
            if (!await DailyTasksService.CreateTask(dailyTask, User.Identity.Name))
                return BadRequest();
            return RedirectToAction("Index", new {date = dailyTask.Date});
        }

        public async Task<IActionResult> Edit(Guid Id)
        {
            
            var dailyTask = await DailyTasksService.GetTaskById(Id);
            ViewData["categories"] = await TaskCategoriesService.GetCategories();
            return View(dailyTask);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DailyTask dailyTask)
        {
            var dailyTasks = await DailyTasksService.GetTasksByUserAndDate(User.Identity.Name, dailyTask.Date);
            if (!dailyTask.IsCompleted && DailyTasksService.CheckTotalEffortOverflow(dailyTasks))
            {
                var newDailyTasks = DailyTasksService.ReplaceTask(dailyTasks, dailyTask);
                if (DailyTasksService.CheckTotalEffortOverflow(newDailyTasks))
                {
                    ModelState.AddModelError("", "The effort is already beyond the limit! Please " +
                    "try to edit, delete or mark as completed other tasks");
                    ViewData["categories"] = await TaskCategoriesService.GetCategories();
                    return View(dailyTask);
                }
            }
            if (!await DailyTasksService.EditTask(dailyTask, User.Identity.Name))
                return BadRequest();
            return RedirectToAction("Index", new { date = dailyTask.Date });
        }

        public async Task<IActionResult> Delete(Guid Id)
        {
            var dailyTask = await DailyTasksService.GetTaskById(Id);
            ViewData["categories"] = await TaskCategoriesService.GetCategories();
            return View(dailyTask);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(Guid Id)
        {
            var dailyTask = await DailyTasksService.GetTaskById(Id);
            if (!await DailyTasksService.DeleteTask(dailyTask))
                return BadRequest();
            return RedirectToAction("Index", new { date = dailyTask.Date });
        }
    }
}

TaskManagement/Views/DailyTasks/Create.cshtml
@*
    Page for task creation
*@
@model DailyTask
@{
    ViewData["Title"] = "Create Task";
    string date = ViewData["date"] as string;
    IEnumerable<TaskCategory> categories = ViewData["categories"] as IEnumerable<TaskCategory>;
}

<div class="container create-task">
    <h1 class="mb-2">Create Your Task | @date</h1>
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        @*hidden fields*@
        <input hidden asp-for="Date" value="@date" />
        <input hidden asp-for="IsCompleted" value="false" />
        <input hidden asp-for="Id" value="null" />
        @*visible fields*@
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Name"></label>
            <div class="col-sm-8">
                <input class="m-2 form-control" asp-for="Name" />
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Description"></label>
            <div class="col-sm-8">
                <textarea class="m-2 form-control" asp-for="Description" rows="5"></textarea>
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Duration"></label>
            <div class="col-sm-8">
                <input class="m-2 form-control" asp-for="Duration" min="1" max="4" step="1" />
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Duration"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Effort"></label>
            <div class="col-sm-8">
                <select class="m-2 form-control text-center" asp-for="Effort" style="cursor: pointer;" >
                    <option value="">-- Select an option --</option>
                    <option value="1">Low</option>
                    <option value="1.5">Medium</option>
                    <option value="2">High</option>
                </select>
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Effort"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="CategoryId"></label>
            <div class="col-sm-8">
                <select class="m-2 form-control text-center" asp-for="CategoryId" style="cursor: pointer;" >
                    <option class="p-2" value="">-- Select an option --</option>
                    @foreach(var category in categories)
                    {
                        <option class="p-2" value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="CategoryId"></span>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <button type="button" id="back-button" data-date="@date" onclick="backToTasksList()" class="btn btn-secondary me-2">Back To List</button>
            <button class="btn btn-success ms-2" type="submit" asp-controller="DailyTasks" asp-action="Create">Submit</button>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

TaskManagement/Views/DailyTasks/Delete.cshtml
@*
    Read only page for viewing task info or delete it
*@
@model DailyTask
@{
    ViewData["Title"] = "Delete Task";
    IEnumerable<TaskCategory> categories = ViewData["categories"] as IEnumerable<TaskCategory>;
}
<div class="container delete-task">
    <h1 class="mb-2">Delete Your Task | @Model.Date</h1>
    <form method="post">
        @*hidden fields*@
        <input hidden asp-for="Id"/>
        @*visible fields*@
        <div class="row align-items-center mb-2">
            <label class="col-sm-4 fw-bold" asp-for="Name"></label>
            <div class="col-sm-8">
                <input class="m-2 form-control" disabled asp-for="Name" />
            </div>
        </div>
        <div class="row align-items-center mb-2">
            <label class="col-sm-4 fw-bold" asp-for="Description"></label>
            <div class="col-sm-8">
                <textarea class="m-2 form-control" disabled asp-for="Description" rows="5"></textarea>
            </div>
        </div>
        <div class="row align-items-center mb-2">
            <label class="col-sm-4 fw-bold" asp-for="Duration"></label>
            <div class="col-sm-8">
                <input class="m-2 form-control" disabled asp-for="Duration" min="1" max="4" step="1" />
            </div>
        </div>
        <div class="row align-items-center mb-2">
            <label class="col-sm-4 fw-bold" asp-for="Effort"></label>
            <div class="col-sm-8">
                <select class="m-2 form-control text-center" disabled asp-for="Effort" >
                    <option value="">-- Select an option --</option>
                    <option value="1">Low</option>
                    <option value="1.5">Medium</option>
                    <option value="2">High</option>
                </select>
            </div>
        </div>
        <div class="row align-items-center mb-2">
            <label class="col-sm-4 fw-bold" asp-for="CategoryId"></label>
            <div class="col-sm-8">
                <select class="m-2 form-control text-center" disabled asp-for="CategoryId" >
                    <option class="p-2" value="">-- Select an option --</option>
                    @foreach(var category in categories)
                    {
                        <option class="p-2" value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="row align-items-center mb-3">
            <label class="col-sm-4 fw-bold" asp-for="IsCompleted">Completed</label>
            <div class="form-check form-switch col-sm-8">
                @* <input id="IsCompleted" hidden checked name="IsCompleted" /> *@
                <input class="form-check-input" disabled asp-for="IsCompleted" style="transform: translateX(90%) scale(1.5);" />
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <button type="button" id="back-button" data-date="@Model.Date" onclick="backToTasksList()" class="btn btn-secondary me-2">Back To List</button>
            <button class="btn btn-danger ms-2" type="submit" asp-controller="DailyTasks" asp-action="Delete">Delete</button>
        </div>
    </form>
</div>

TaskManagement/Views/DailyTasks/Edit.cshtml
@*
    Page for task editing
*@
@model DailyTask
@{
    ViewData["Title"] = "Edit Task";
    IEnumerable<TaskCategory> categories = ViewData["categories"] as IEnumerable<TaskCategory>;
}
<div class="container edit-task">
    <h1 class="mb-2">Edit Your Task | @Model.Date</h1>
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        @*hidden fields*@
        <input hidden asp-for="Date"/>
        <input hidden asp-for="Id"/>
        @*visible fields*@
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Name"></label>
            <div class="col-sm-8">
                <input class="m-2 form-control" asp-for="Name" />
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Description"></label>
            <div class="col-sm-8">
                <textarea class="m-2 form-control" asp-for="Description" rows="5"></textarea>
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Duration"></label>
            <div class="col-sm-8">
                <input class="m-2 form-control" asp-for="Duration" min="1" max="4" step="1" />
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Duration"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="Effort"></label>
            <div class="col-sm-8">
                <select class="m-2 form-control text-center" asp-for="Effort" style="cursor: pointer;" >
                    <option value="">-- Select an option --</option>
                    <option value="1">Low</option>
                    <option value="1.5">Medium</option>
                    <option value="2">High</option>
                </select>
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="Effort"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="CategoryId"></label>
            <div class="col-sm-8">
                <select class="m-2 form-control text-center" asp-for="CategoryId" style="cursor: pointer;" >
                    <option class="p-2" value="">-- Select an option --</option>
                    @foreach(var category in categories)
                    {
                        <option class="p-2" value="@category.Id">@category.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="mb-2">
            <span class="text-danger" asp-validation-for="CategoryId"></span>
        </div>
        <div class="row align-items-center">
            <label class="col-sm-4 fw-bold" style="cursor: pointer;" asp-for="IsCompleted">Completed</label>
            <div class="form-check form-switch col-sm-8">
                @* <input id="IsCompleted" hidden checked name="IsCompleted" /> *@
                <input class="form-check-input" asp-for="IsCompleted" style="transform: translateX(90%) scale(1.5); cursor:pointer;" />
            </div>
        </div>
        <div class="mb-3">
            <span class="text-danger" asp-validation-for="IsCompleted"></span>
        </div>
        <div class="d-flex align-items-center justify-content-center">
            <button type="button" id="back-button" data-date="@Model.Date" onclick="backToTasksList()" class="btn btn-secondary me-2">Back To List</button>
            <button class="btn btn-success ms-2" type="submit" asp-controller="DailyTasks" asp-action="Edit">Submit</button>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

TaskManagement/Views/DailyTasks/Index.cshtml
@*
    Main page where daily tasks are showed
*@
@using TaskManagement.ViewModels.DailyTasks
@model IEnumerable<DailyTask>

@{
    ViewData["Title"] = "Daily Tasks";
    Report report = ViewData["report"] as Report;
    string date = ViewData["date"] as string;
}

<div class="container daily-tasks-content">
    <h1 class="mb-2">Manage Your Daily Tasks</h1>
    <input id="datepicker" onchange="dateChanged()" class="form-control mb-3" type="date" style="cursor: pointer;" value="@date" />
    @if (Model != null && Model.Count() > 0)
    {
        @*render daily tasks and report section*@
        <table class="table table-borderless table-hover text-center">
            <thead>
                <tr>
                    <th scope="col">
                        Completed
                    </th>
                    <th scope="col">
                        Name
                    </th>
                    <th scope="col">
                        Category
                    </th>
                    <th scope="col">
                        Duration
                    </th>
                    <th scope="col">
                        Effort
                    </th>
                    <th scope="col">
                        Description
                    </th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var dailyTask in Model)
                {
                    @*mapping task effort*@
                    string taskEffortString;
                    if(dailyTask.Effort == 1)
                    {
                        taskEffortString = "Low";
                    }
                    else if (dailyTask.Effort == 1.5)
                    {
                        taskEffortString = "Medium";
                    }
                    else if (dailyTask.Effort == 2)
                    {
                        taskEffortString = "High";
                    }
                    else
                    {
                        taskEffortString = "Unknown";
                    }

                    <tr>
                        <td class="position-relative" style="background-color: @dailyTask.Category.RgbaColor">
                            @if(dailyTask.IsCompleted)
                            {
                                <i class="bi bi-check2 position-absolute text-success" style="top: 50%; left: 50%; transform: translate(-50%, -50%) scale(1.5); border-bottom: 2px solid white;"></i>
                            }
                            else
                            {
                                <i class="bi bi-x position-absolute text-danger" style="top: 50%; left: 50%; transform: translate(-50%, -50%) scale(1.5); border-bottom: 2px solid white;"></i>
                            }
                        </td>
                        <td style="background-color: @dailyTask.Category.RgbaColor">
                            @if(dailyTask.Name.Length > 15)
                            {
                                <p style="margin-top: 1rem;">@dailyTask.Name.Substring(0, 15)...</p>
                            }
                            else
                            {
                                <p style="margin-top: 1rem;">@dailyTask.Name</p>
                            }
                        </td>
                        <td style="background-color: @dailyTask.Category.RgbaColor">
                            <p style="margin-top: 1rem;">@dailyTask.Category.Name</p>
                        </td>
                        <td style="background-color: @dailyTask.Category.RgbaColor">
                            <p style="margin-top: 1rem;">@dailyTask.Duration</p>
                        </td>
                        <td style="background-color: @dailyTask.Category.RgbaColor">
                            <p style="margin-top: 1rem;">@taskEffortString</p>
                        </td>
                        <td style="background-color: @dailyTask.Category.RgbaColor">
                            @if (dailyTask.Description?.Length > 15)
                            {
                                <p style="margin-top: 1rem;">@dailyTask.Description.Substring(0, 15)...</p>
                            }
                            else
                            {
                                <p style="margin-top: 1rem;">@dailyTask.Description</p>
                            }
                        </td>
                        <td style="background-color: @dailyTask.Category.RgbaColor">
                            <form method="get">
                                <button style="margin-top: 0.5rem;" type="submit" class="btn btn-light" asp-controller="DailyTasks" asp-action="Edit" asp-route-id="@dailyTask.Id">Edit</button>
                            </form>
                        </td>
                        <td style="background-color: @dailyTask.Category.RgbaColor">
                            <form method="get">
                                <button style="margin-top: 0.5rem;" type="submit" class="btn btn-light" asp-controller="DailyTasks" asp-action="Delete" asp-route-id="@dailyTask.Id">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="mt-2 d-flex align-items-center justify-content-center">
            <button id="back-button" class="btn btn-success" data-date="@date" onclick="goToCreatePage()">Create Daily Task</button>
        </div>
        @*report section*@
        <div class="d-flex flex-wrap justify-content-evenly">
            @{
                ViewData["report-title"] = "Total Effort";
                ViewData["report-type"] = "totalEffort";
                ViewData["RgbaColor"] = "rgba(129,140,248,0.5)";
            }
            <partial name="_ReportItem" />

            @{
                ViewData["report-type"] = "completionPercentage";
                ViewData["report-title"] = "Completion %";
                ViewData["RgbaColor"] = "rgba(74,222,128,0.5)";
            }
            <partial name="_ReportItem" />

            @{ViewData["report-type"] = "category";}
            @foreach(var category in report.Categories)
            {
                ViewData["report-title"] = category.Key + " %";
                ViewData["RgbaColor"] = Model.Where(dt => dt.Category.Name.Equals(category.Key))
                .Select(dt => new
                {
                    RgbaColor = dt.Category.RgbaColor
                })
                .FirstOrDefault()
                ?.RgbaColor;
                string categoryPercentage = category.Value.ToString();
                if (categoryPercentage.Length > 4)
                    categoryPercentage = categoryPercentage.Substring(0, 4);
                ViewData["category-percentage"] = categoryPercentage;
                <partial name="_ReportItem" />
            }
        </div>
    }
    else
    {
        <div class="d-flex align-items-center justify-content-start daily-tasks-content">
            <p class="m-0">There aren't any tasks planned for today, please create them by pressing</p>
            <button id="back-button" class="btn btn-success ms-2" data-date="@date" onclick="goToCreatePage()">Create Daily Task</button>
        </div>
    }
</div>