TaskManagement/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
//using TaskManagement.Data;
using TaskManagement.IServices;
using TaskManagement.ViewModels.Login;

namespace TaskManagement.Controllers
{
    public class LoginController : Controller
    {
        private ILoginService LoginService { get; set; }

        public LoginController(ILoginService loginService)
        {
            LoginService = loginService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            string? AccessDeniedError = TempData["Access Denied"] as string;
            if (AccessDeniedError != null)
                ModelState.AddModelError("", AccessDeniedError);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Credentials credentials)
        {
            if(!ModelState.IsValid || ! await LoginService.Login(credentials, HttpContext))
            {
                ModelState.AddModelError("", "Username or Password are not correct!");
                return View(credentials);
            }

            return Redirect("/Home");
        }

        public async Task<IActionResult> Logout()
        {
            await LoginService.Logout(HttpContext);
            return Redirect("/Home");
        }

        public async Task<IActionResult> AccessDenied()
        {
            await LoginService.Logout(HttpContext);
            TempData["Access Denied"] = "Access Denied!";
            return RedirectToAction("Index");
        }
    }
}

TaskManagement/Controllers/TaskCategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaskManagement.IServices;
using TaskManagement.Models;
using TaskManagement.ViewModels.TaskCategories;

namespace TaskManagement.Controllers
{
    [Authorize(Policy = "AdminAccount")]
    public class TaskCategoriesController : Controller
    {
        private ITaskCategoriesService TaskCategoriesService { get; set; }
        public TaskCategoriesController(ITaskCategoriesService taskCategoriesService)
        {
            TaskCategoriesService = taskCategoriesService;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await TaskCategoriesService.GetCategories();
            Report report = TaskCategoriesService.GenerateReport(categories);
            ViewData["report"] = report;
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TaskCategory taskCategory)
        {
            if (!await TaskCategoriesService.CreateTaskCategory(taskCategory))
                return BadRequest(ModelState);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(Guid Id)
        {
            var taskCategory = await TaskCategoriesService.GetTaskCategoryById(Id);
            return View(taskCategory);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TaskCategory category)
        {
            if(! await TaskCategoriesService.EditTaskCategory(category))
                return BadRequest(ModelState);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid Id)
        {
            var taskCategory = await TaskCategoriesService.GetTaskCategoryById(Id);
            return View(taskCategory);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(Guid Id)
        {
            if (!await TaskCategoriesService.DeleteTaskCategory(Id))
                return BadRequest(ModelState);
            return RedirectToAction("Index");
        }
    }
}

TaskManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/TaskManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css" />
</head>
<body>
    <div id="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 align-items-center">
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <partial name="_NavLinks" />
                        </ul>
                    </div>
                    <div>
                        <partial name="_LoggingSection"/>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - TaskManagement 
                - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <div id="warning-message" class="text-danger">
        Please change screen orientation to <mark>landscape (horizontal)</mark> 
        in order to use the application on mobile!
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagement/Views/Shared/_LoggingSection.cshtml
@using System.Security.Claims;

@if (User.Identity.IsAuthenticated)
{
    Claim claim = User.Claims.Where(c => c.Type == ClaimTypes.Role).FirstOrDefault();
    string Role = "Default";
    if (claim != null)
        Role = claim.Value;

    <div class="d-flex align-items-center">
        <strong>@User.Identity.Name (@Role)</strong>
        <a class="btn btn-danger ms-2" asp-controller="Login" asp-action="Logout">Logout</a>
    </div>
}
else {
    <a class="btn btn-success" asp-controller="Login" asp-action="Index">Login</a>
}

TaskManagement/Views/Shared/_NavLinks.cshtml
@* Navigation links displayed based on the user role *@

@using System.Security.Claims;

@if(User.Identity.IsAuthenticated) {
    Claim claim = User.Claims.Where(c => c.Type == ClaimTypes.Role).FirstOrDefault();
    string Role = "Default";
    if (claim != null)
        Role = claim.Value;
    if (Role == "Normal User" || Role == "Admin")
    {
        <li class="nav-item">
            <a class="nav-link text-dark" onclick="viewDailyTasks(event)" style="cursor: pointer;">Daily Tasks</a>
        </li>
    }
    if (Role == "Admin")
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="TaskCategories" asp-action="Index">Task Categories</a>
        </li>
    }
}

TaskManagement/Views/Shared/_ReportItem.cshtml
@using TaskManagement.ViewModels.DailyTasks

@{
    Report report = ViewData["report"] as Report;
    string reportTitle = ViewData["report-title"] as string;
    string reportType = ViewData["report-type"] as string;
    string rgbaColor = ViewData["RgbaColor"] as string;
    if (report == null)
        throw new Exception("Report is null but there are values in the Model");
}

@if(reportType.Equals("totalEffort"))
{
    string totalEffortString = report.TotalEffort.ToString();
    if (totalEffortString.Length > 4)
    {
        totalEffortString = totalEffortString.Substring(0, 4);
    }
    string effort = totalEffortString + "/" + "18";

    <div class="m-4 report-item">
        <div class="parent" style="background-color: @rgbaColor">
            <div class="child" data-percentage="@effort"></div>
        </div>
        <div class="title-container">
            <h2 class="report-title" style="border-bottom: 2px solid @rgbaColor">@reportTitle</h2>
        </div>
        <div class="text-danger mt-3" asp-validation-summary="ModelOnly"></div>
    </div>
}
else if(reportType.Equals("completionPercentage"))
{
    string percentageCompletion = report.PercentageCompletion.ToString();
    if (percentageCompletion.Length > 4)
    {
        percentageCompletion = percentageCompletion.Substring(0, 4);
    }

    <div class="m-4 report-item">
        <div class="parent" style="background-color: @rgbaColor">
            <div class="child" data-percentage="@percentageCompletion"></div>
        </div>
        <div class="title-container">
            <h2 class="report-title" style="border-bottom: 2px solid @rgbaColor">@reportTitle</h2>
        </div>
    </div>
}
else if(reportType.Equals("category"))
{
    string categoryPercentage = ViewData["category-percentage"] as string;
    if (categoryPercentage.Length > 4)
    {
        categoryPercentage = categoryPercentage.Substring(0, 4);
    }

    <div class="m-4 report-item">
        <div class="parent" style="background-color: @rgbaColor">
            <div class="child" data-percentage="@categoryPercentage"></div>
        </div>
        <div class="title-container">
            <h2 class="report-title" style="border-bottom: 2px solid @rgbaColor">@reportTitle</h2>
        </div>
    </div>
}
else {
    <p class="text-danger">Something's wrong, report type unknown</p>
}